# Generated by Django 5.1.6 on 2025-02-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunos',
            old_name='data_nacimento',
            new_name='data_nascimento',
        ),
    ]
